### ISSUE TITLE
How is syn_rot_on_garment.pt generated?

### ISSUE THREAD

**Issue by bryanbocao** [ZuoCX1996/Loose-Inertial-Poser#1]
Hi, thanks for sharing the awesome work!

May I know how to generate the ```syn_rot_on_garment.pt``` file?

When I ran
```
(looseposer) brcao@aw2:/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser$ python3 train_SemoAE.py
```
I got
```
running load_data
Traceback (most recent call last):
  File "train_SemoAE.py", line 16, in <module>
    dataset = SynPairedIMUData.load_data(folder_path=paths.amass_dir, shuffle=True, clothes_imu_calibration=True)
  File "/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser/Aplus/tools/annotations.py", line 7, in wrapper
    ret = fn(*args, **kwargs)
  File "/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser/my_data.py", line 510, in load_data
    rot_imu = amass_read(os.path.join(folder_path, 'syn_rot_on_garment.pt'))
  File "/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser/my_data.py", line 79, in amass_read
    data = torch.load(path)
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/processed_AMASS_upper/syn_rot_on_garment.pt'
```
Before that I have processed ```AMASS``` dataset by running
```python3 AMASS_preprocess.py```
```
if __name__ == '__main__':
    process_amass()
```
but the ```process_amass()``` only generates these files
```
    torch.save(out_pose, os.path.join(paths.amass_dir, 'pose.pt'))
    torch.save(out_shape, os.path.join(paths.amass_dir, 'shape.pt'))
    torch.save(out_tran, os.path.join(paths.amass_dir, 'tran.pt'))
    torch.save(out_joint, os.path.join(paths.amass_dir, 'joint.pt'))
    torch.save(out_vrot, os.path.join(paths.amass_dir, 'vrot.pt'))
    torch.save(out_vacc, os.path.join(paths.amass_dir, 'vacc.pt'))
```
Thanks in advance!

**Comment by ZuoCX1996** [comment]
The [syn_rot_on_garment.pt] contains IMU orientation data synthesized from the garment model using TailorNet: https://github.com/chaitanya100100/TailorNet

The synthesized IMU data files are too large to upload to GitHub, you can download them using the following Baidu Cloud link:
链接: https://pan.baidu.com/s/1UmFCHvt3pqIYixuuCqBqWg?pwd=nmyr 提取码: nmyr

I hope this is helpful! And you can also try IMU synthesize with different body shape and garment style using TailorNet. You can check the supp for more details!

**Comment by bryanbocao** [comment]
> The [syn_rot_on_garment.pt] contains IMU orientation data synthesized from the garment model using TailorNet: https://github.com/chaitanya100100/TailorNet
> 
> The synthesized IMU data files are too large to upload to GitHub, you can download them using the following Baidu Cloud link: 链接: https://pan.baidu.com/s/1UmFCHvt3pqIYixuuCqBqWg?pwd=nmyr 提取码: nmyr
> 
> I hope this is helpful! And you can also try IMU synthesize with different body shape and garment style using TailorNet. You can check the supp for more details!

Hi @ZuoCX1996 thank you for providing the link!

I could not log in to my 百度网盘 account today. It might take a few days for me to get back my account. Will check that later. It would be appreciated if you can upload them to another Cloud Drive services like OneDrive, or send me via email: boccao@cs.stonybrook.edu. Thanks!

**Comment by ZuoCX1996** [comment]
Hi! You can try this OneDrive link: https://1drv.ms/f/c/d6cd78cd7ce83043/Etl3HdtmHl5Dn05NQ-ZKScMBYsCo4gTef7Io3JVZb07nxQ?e=UMXx0e

**Comment by bryanbocao** [comment]
Hi @ZuoCX1996, thanks for providing the data in OneDrive! I can load the data but it the shape seems incorret:

```
(looseposer) brcao@aw2:/media/brcao/eData4TB1/Repos/bryanbocao/sparseimu/Loose-Inertial-Poser$ python3 train_SemoAE.py
running load_data
Traceback (most recent call last):
  File "train_SemoAE.py", line 16, in <module>
    dataset = SynPairedIMUData.load_data(folder_path=paths.amass_dir, shuffle=True, clothes_imu_calibration=True)
  File "/media/brcao/eData4TB1/Repos/bryanbocao/sparseimu/Loose-Inertial-Poser/Aplus/tools/annotations.py", line 7, in wrapper
    ret = fn(*args, **kwargs)
  File "/media/brcao/eData4TB1/Repos/bryanbocao/sparseimu/Loose-Inertial-Poser/my_data.py", line 541, in load_data
    acc_imu = acc_imu.reshape(data_len, -1)
RuntimeError: shape '[5200061, -1]' is invalid for input of size 84990036
```

It would be great if you can help with that.

Thanks!

**Comment by ZuoCX1996** [comment]
Try my syn IMU data on amass! (100% match my TailorNet syn IMU data):

https://1drv.ms/f/c/d6cd78cd7ce83043/Eqz0kup3E0NEpr0j0A9R8DIBb4Jr0D-PS2MnQtYKJjCdzQ?e=urBJ6m

**Comment by bryanbocao** [comment]
When I run
```
Loose-Inertial-Poser$ python3 train_SemoAE.py 
```
I get this error
```
running load_data
done | time cost:13.641 s
6728377
354125
Traceback (most recent call last):
  File "train_SemoAE.py", line 34, in <module>
    evaluator = SemoAEEvaluator.from_trainer(trainner, data_eval=data_test)
AttributeError: type object 'SemoAEEvaluator' has no attribute 'from_trainer'
```

Then in the ```my_trainer.py``` file I changed ```class SemoAEEvaluator(BaseEvaluator):``` to
```
class SemoAEEvaluator(MyEvaluator):
```

or maybe add this method
```
    @classmethod
    def from_trainer(cls, trainer, data_eval, rot_type='r6d'):
        return cls(model=trainer.model, loss_func=trainer.loss_func, batch_size=trainer.batch_size, data=data_eval, rot_type=rot_type)
```
in
```
class SemoAEEvaluator(BaseEvaluator):
```

**Comment by bryanbocao** [comment]
> Try my syn IMU data on amass! (100% match my TailorNet syn IMU data):
> 
> https://1drv.ms/f/c/d6cd78cd7ce83043/Eqz0kup3E0NEpr0j0A9R8DIBb4Jr0D-PS2MnQtYKJjCdzQ?e=urBJ6m

Thanks! I have put your data in the ```Loose-Inertial-Poser/data/processed_AMASS_upper``` folder.

When I ran
```
Loose-Inertial-Poser$ python3 train_SemoAE.py 
```
I got this error
```
running load_data
done | time cost:13.641 s
6728377
354125
Traceback (most recent call last):
  File "train_SemoAE.py", line 34, in <module>
    evaluator = SemoAEEvaluator.from_trainer(trainner, data_eval=data_test)
AttributeError: type object 'SemoAEEvaluator' has no attribute 'from_trainer'
```

Then in the ```my_trainer.py``` file I changed ```class SemoAEEvaluator(BaseEvaluator):``` to
```
class SemoAEEvaluator(MyEvaluator):
```
but I got
```
Loose-Inertial-Poser$ python3 train_SemoAE.py 
running load_data
done | time cost:13.51 s
6728377
354125
Traceback (most recent call last):
  File "train_SemoAE.py", line 34, in <module>
    evaluator = SemoAEEvaluator.from_trainer(trainner, data_eval=data_test)
  File "/media/brcao/eData4TB1/Repos/bryanbocao/sparseimu/Loose-Inertial-Poser/my_trainer.py", line 298, in from_trainer
    return cls(model=trainer.model, loss_func=trainer.loss_func, batch_size=trainer.batch_size, data=data_eval, rot_type=rot_type)
TypeError: __init__() got an unexpected keyword argument 'rot_type'
```

Then I changed ```class SemoAEEvaluator(MyEvaluator):``` back to ```class SemoAEEvaluator(BaseEvaluator):``` and added this method 
```
    @classmethod
    def from_trainer(cls, trainer, data_eval):
        return cls(model=trainer.model, loss_func=trainer.loss_func, batch_size=trainer.batch_size, data=data_eval)
```
in
```
class SemoAEEvaluator(BaseEvaluator):
```

Then it seemed to be training correctly:
```
Loose-Inertial-Poser$ python3 train_SemoAE.py 
running load_data
done | time cost:13.665 s
6728377
354125
iter 691 | 691tight angle error tensor(128.9084)
loose angle error tensor(123.5810)
tight acc error tensor(0.2102)
loose acc error tensor(0.1863)
mmd tensor(2.2321)
running run
iter 691 | 691tight angle error tensor(3.7269)
loose angle error tensor(3.5269)
tight acc error tensor(0.0809)
loose acc error tensor(0.0559)
mmd tensor(0.0158)
mmd_loss: tensor(0.0115, grad_fn=<DivBackward0>)
| epoch: 1 | tight_err_train: 5.25876 | loose_err_train: 4.93271 | tight_err_eval: 3.72692 | loose_err_eval: 3.5269 |
done | time cost:603.174 s
saving checkpoint ...done
touch ./log/SemoAE.xlsx
running run
iter 10105 | 13141
```

Let me know if I did it correctly. Thanks!

**Comment by ZuoCX1996** [comment]
Yes! That's correct!
