### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './log/LIP.xlsx'

### ISSUE THREAD

**Issue by bryanbocao** [ZuoCX1996/Loose-Inertial-Poser#2]
When I ran
```
python3 train_poser.py 
```
I got this error message:
```
(looseposer) brcao@aw2:/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser$ CUDA_VISIBLE_DEVICES=1 python3 train_poser.py 
running load_data
done | time cost:35.953 s
running load_data
loading s3_zipped_specific
loading s2_zipped_specific
loading s4_open_random
loading s2_zipped_random
loading s1_zipped_specific
loading s5_zipped_specific
loading s4_zipped_specific
loading s3_open_random
loading s1_open_random
loading s1_zipped_random
loading s4_zipped_random
loading s3_open_specific
loading s2_open_random
loading s4_open_specific
loading s5_open_specific
loading s5_open_random
loading s2_open_specific
loading s1_open_specific
loading s5_zipped_random
loading s3_zipped_random
torch.Size([424998, 4, 3, 3])
torch.Size([424998, 4, 3])
torch.Size([424998, 24, 3])
torch.Size([424998, 24, 3])
done | time cost:2.161 s
Restore from ./checkpoint/SemoAE_10.pth
running run
iter 10155 | 10155
tensor([16.4404, 11.8717,  5.7593,  5.2681, 19.3534, 19.6080, 30.6949, 30.2666,
        30.8232, 30.2794])
| epoch: 1 | loss_train: 0.02062 | loss_eval: 0.04834 | ang_err: 20.0365 |
done | time cost:1432.162 s
saving checkpoint ...done
Traceback (most recent call last):
  File "train_poser.py", line 63, in <module>
    trainer.log_export(f'./log/{model_name}.xlsx')
  File "/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser/Aplus/runner/base_trainer.py", line 59, in log_export
    self.log_manager.to_excel(path)
  File "/media/brcao/eData4TB1/Repos/bryanbocao/Loose-Inertial-Poser/Aplus/utils/log_manager.py", line 37, in to_excel
    df_log.to_excel(f'{path}', index=False)
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 57, in __init__
    engine_kwargs=engine_kwargs,
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 926, in __init__
    path, mode, storage_options=storage_options, is_text=False
  File "/home/brcao/Apps/miniconda3/envs/looseposer/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: './log/LIP.xlsx'
```

**Comment by bryanbocao** [comment]
```
Aplus/runner/base_trainer.py
```
```
class BaseTrainer:
    def log_export(self, path):
        """
        Export training log.
        :param path: e.g. './log.xlsx'
        :return: None
        """
        cmd = f'touch {path}'
        os.system(cmd); print(cmd)
        self.log_manager.to_excel(path)
```
